# Take our settings from the example directory's main analysis_options.yaml
# file. If necessary for a particular example, this file can also include
# overrides for individual lints.

include: ../../analysis_options.yaml

analyzer:
  errors:
    # Ignored since ignore_for_files can't be hidden in diff excerpts yet
    missing_required_argument: ignore
