# Take our settings from the example_utils analysis_options.yaml file.
# If necessary for a particular example, this file can also include
# overrides for individual lints.

include: package:example_utils/analysis.yaml

analyzer:
  errors:
    # Ignored since ignore_for_files can't be hidden in diff excerpts yet
    missing_required_argument: ignore
