name: native_debugging
description: Demonstration of native code debugging
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  url_launcher: ^6.1.12

dev_dependencies:
  example_utils:
    path: ../../example_utils
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
