name: basic_hero_transition
description: Shows how to create a simple or Hero animation using the Hero class directly.

dependencies:
  flutter:
    sdk: flutter
  material_icons_font: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - images/flippers-alpha.png
