name: basic_flying_transition
description: Shows how to create a simple shared element (or Hero) transition using the Hero class directly.

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/flippers-alpha.png
