name: long_lists
description: Example for long_lists cookbook recipe

environment:
  sdk: ^3.1.0-0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
