name: debugging
description: A Flutter debugging example.
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  example_utils:
    path: ../../example_utils
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
