name: container
description: Demonstrates the Container widget.

dependencies:
  flutter:
    sdk: flutter
  material_icons_font: ^0.1.1

flutter:
  assets:
    - images/pic1.jpg
    - images/pic2.jpg
    - images/pic3.jpg
    - images/pic4.jpg
