name: tabs
description: Sample code for tabs cookbook recipe.

environment:
  sdk: ^3.3.0-0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  example_utils:
    path: ../../../example_utils

flutter:
  uses-material-design: true
