name: state_mgmt
description: Sample state management code.

version: 1.0.0+1

environment:
  sdk: ^3.0.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2
  test: ^1.24.1

flutter:
  uses-material-design: true
