name: row_expanded
description: Demonstrates a Row widget containing an Expanded widget with a flex factor of 2.

dependencies:
  flutter:
    sdk: flutter
  material_icons_font: ^0.1.1

flutter:
  assets:
    - images/pic1.jpg
    - images/pic2.jpg
    - images/pic3.jpg
