name: column
description: Demonstrates the column widget.

dependencies:
  flutter:
    sdk: flutter
  material_icons_font: ^0.1.1

flutter:
  assets:
    - images/pic1.jpg
    - images/pic2.jpg
    - images/pic3.jpg
