name: lakes_interactive
description: Demonstrates adding interactivity to the "Lakes" app.

dependencies:
  flutter:
    sdk: flutter
  material_icons_font: ^0.1.1

flutter:
  assets:
    - images/lake.jpg
