name: constraints
description: example for ui/layout/constraints
version: 1.0.0

environment:
  sdk: ^3.0.3

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
