name: codelab_web
description: Sample codelab for web

publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.3.0-0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  example_utils:
    path: ../../example_utils
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
