name: interactive
description: >-
  Sample app from "Adding interactivity":
  https://docs.flutter.dev/ui/interactivity.
version: 1.0.0

environment:
  sdk: ^3.2.0-0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  example_utils:
    path: ../../../example_utils
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/lake.jpg
