name: basic_staggered
description: A new Flutter project.

environment:
  sdk: ^3.1.0-0

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

dev_dependencies:
  example_utils:
    path: ../../example_utils
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
