name: hero_animations
description: Hero animations

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^6.0.7

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
