name: radial_hero_animation_animate_rectclip
description: Shows how to apply a radial transformation to the Hero as it animates to the new route.

dependencies:
  flutter:
    sdk: flutter
  material_icons_font: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - images/beachball-alpha.png
    - images/binoculars-alpha.png
    - images/chair-alpha.png
