name: basic_radial_transition
description: Shows how to apply a radial transformation to an element (the Hero) that's shared by both pages in the transition.

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/beachball-alpha.png
    - images/binoculars-alpha.png
    - images/chair-alpha.png
