name: radial_transition_animate_rectclip
description: Shows how to transition from one page to another using radial motion while animating the rectclip, as well as the ovalclip.

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/beachball-alpha.png
    - images/binoculars-alpha.png
    - images/chair-alpha.png
