name: hero_animation
description: Shows how to create a simple Hero transition.

dependencies:
  flutter:
    sdk: flutter
  material_icons_font: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - images/flippers-alpha.png
