name: visual_debugging_example
publish_to: none
description: Examples of visual debugging
version: 1.0.0

environment:
  sdk: ^3.1.0-0

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  example_utils:
    path: ../example_utils
  flutter_test:
    sdk: flutter
