name: delete_data
description: Delete Data

environment:
  sdk: ^3.1.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0

dev_dependencies:
  example_utils:
    path: ../../../example_utils

flutter:
  uses-material-design: true
