name: focus
description: Sample focus system code.
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  
dev_dependencies:
  example_utils:
    path: ../../../example_utils

flutter:
  uses-material-design: true
