name: pavlova
description: Demonstrates building a layout for the Strawberry Pavlova app.

dependencies:
  flutter:
    sdk: flutter
  material_icons_font: ^0.1.1

flutter:
  assets:
    - images/pavlova.jpg
