name: google_sign_in_example
publish_to: none

environment:
  sdk: ^3.1.0

dependencies:
  collection: any
  extension_google_sign_in_as_googleapis_auth: ^2.0.11
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.5
  googleapis: ^11.4.0
  http: ^1.1.0

dev_dependencies:
  example_utils:
    path: ../example_utils
