name: error_reporting
description: error reporting

environment:
  sdk: ^3.2.0-0

dependencies:
  flutter:
    sdk: flutter
  sentry_flutter: ^7.0.0

dev_dependencies:
  example_utils:
    path: ../../../example_utils
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
