name: mocking
description: Use the Mockito package to mimic the behavior of services for testing.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
