name: state_mgmt
description: Sample state management code.
publish_to: none

environment:
  sdk: ^3.2.0

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5

dev_dependencies:
  example_utils:
    path: ../../example_utils
  flutter_test:
    sdk: flutter
  test: ^1.24.6

flutter:
  uses-material-design: true
