name: spaced_items
description: Example for spaced_items cookbook recipe

environment:
  sdk: ^3.0.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
