- platform: 'Windows'
  x86: '<span class="material-symbols" style="color: #158477;">verified</span>'
  x64: '<span class="material-symbols" style="color: #158477;">verified</span>'
  arm32: '<span class="material-symbols" style="color: #D43324">dangerous</span>'
  arm64: '<span class="material-symbols" style="color: #13C2AD">gpp_maybe</span>'
  risc-v: '<span class="material-symbols" style="color: #D43324">dangerous</span>'
- platform: 'Linux'
  x86: '<span class="material-symbols" style="color: #158477;">verified</span>'
  x64: '<span class="material-symbols" style="color: #158477;">verified</span>'
  arm32: '<span class="material-symbols" style="color: #158477;">verified</span>'
  arm64: '<span class="material-symbols" style="color: #158477;">verified</span> '
  risc-v: '<span class="material-symbols" style="color: #13C2AD">gpp_maybe</span>'
- platform: 'macOS'
  x86: '<span class="material-symbols" style="color: #D43324">dangerous</span>'
  x64: '<span class="material-symbols" style="color: #158477;">verified</span>'
  arm32: '<span class="material-symbols" style="color: #DADCE0">do_not_disturb_on</span>'
  arm64: '<span class="material-symbols" style="color: #158477;">verified</span> '
  risc-v: '<span class="material-symbols" style="color: #DADCE0">do_not_disturb_on</span>'
- platform: 'iOS'
  x86: '<span class="material-symbols" style="color: #DADCE0">do_not_disturb_on</span>'
  x64: '<span class="material-symbols" style="color: #DADCE0">do_not_disturb_on</span>'
  arm32: '<span class="material-symbols" style="color: #DADCE0">do_not_disturb_on</span>'
  arm64: '<span class="material-symbols" style="color: #158477;">verified</span> '
  risc-v: '<span class="material-symbols" style="color: #DADCE0">do_not_disturb_on</span>'
- platform: 'Android'
  x86: '<span class="material-symbols" style="color: #DADCE0">do_not_disturb_on</span>'
  x64: '<span class="material-symbols" style="color: #DADCE0">do_not_disturb_on</span>'
  arm32: '<span class="material-symbols" style="color: #DADCE0">do_not_disturb_on</span>'
  arm64: '<span class="material-symbols" style="color: #158477;">verified</span> '
  risc-v: '<span class="material-symbols" style="color: #DADCE0">do_not_disturb_on</span>'