- platform: 'Android SDK'
  chipsets: 'x64, Arm32, Arm64'
  supported: '21 to 34'
  ci-tested: '21 to 34'
  unsupported: '20 and earlier'
- platform: 'iOS'
  chipsets: 'Arm64'
  supported: '12 to 18'
  ci-tested: '17'
  unsupported: '11 and earlier'
- platform: 'macOS'
  chipsets: 'x64, Arm64'
  supported: 'Mojave (10.14) to Sequoia (15)'
  ci-tested: 'Ventura (13), Sonoma (14)'
  unsupported: 'High Sierra (10.13) and earlier'
- platform: 'Windows'
  chipsets: 'x64, Arm64'
  supported: '10, 11'
  ci-tested: '10'
  unsupported: '8 and earlier'
- platform: 'Debian (Linux)'
  chipsets: 'x64, Arm64'
  supported: '10, 11, 12'
  ci-tested: '11, 12'
  unsupported: '9 and earlier'
- platform: 'Ubuntu (Linux)'
  chipsets: 'x64, Arm64'
  supported: '20.04 LTS to 24.04 LTS'
  ci-tested: '20.04 LTS, 22.04 LTS'
  unsupported: '23.10 and earlier non-LTS'
- platform: 'Chrome (Web)'
  chipsets: 'N/A'
  supported: '[Latest 2](https://chromereleases.googleblog.com/search/label/Stable%20updates)'
  ci-tested: '119, 125'
  unsupported: '95 and earlier'
- platform: 'Firefox (Web)'
  chipsets: 'N/A'
  supported: '106 and newer'
  ci-tested: '106'
  unsupported: '98 and earlier'
- platform: 'Safari (Web)'
  chipsets: 'N/A'
  supported: '15.6 and newer'
  ci-tested: '15.6'
  unsupported: '15.5 and earlier'
- platform: 'Edge (Web)'
  chipsets: 'N/A'
  supported: '[Latest 2](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel)'
  ci-tested: 119, 125
  unsupported: '95 and earlier'
