name: scrolling
description: A new Flutter project.

environment:
  sdk: ^3.0.3

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.15
  path: ^1.8.3
  flutter_test:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.2
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
