name: sqlite
description: SQLITE

environment:
  sdk: ^3.2.0-0

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3

dev_dependencies:
  example_utils:
    path: ../../../example_utils
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
