name: animation
description: >-
  Sample app from "Animations tutorial":
  https://docs.flutter.dev/ui/animations/tutorial.
version: 1.0.0

environment:
  sdk: ^3.3.0-0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  example_utils:
    path: ../../example_utils
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
