name: handling_taps
description: Example on handling_taps cookbook recipe.

environment:
  sdk: ^3.3.0-0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  example_utils:
    path: ../../../example_utils

flutter:
  uses-material-design: true
