name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"

# Declare default permissions as read only.
permissions: read-all

env:
  NODE_ENV: production
  NODE_VERSION: 17

jobs:

  test:
    runs-on: ubuntu-latest
    if: github.repository == 'flutter/website'
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Beta channel"
            channel: beta
            experimental: true
          - name: "Stable channel"
            channel: stable
            experimental: false
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      - name: Test
        run: make test
        env:
          TEST_TARGET_CHANNEL: ${{ matrix.channel }}
        continue-on-error: ${{ matrix.experimental }}

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push'
      && github.ref == 'refs/heads/main'
      && github.repository == 'flutter/website'
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
        with:
          submodules: "recursive"
      - name: Install Node
        uses: actions/setup-node@9ced9a43a244f3ac94f13bfd896db8c8f30da67a
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install firebase tools
        run: npm install -g firebase/firebase-tools#23dc81fd065f4cfaa172cff535cafdd9a8c11c23
      - name: Build
        run: make build
        env:
          DISABLE_TESTS: 1
      - name: Deploy
        run: make deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_ALIAS: default
