name: build

on:
  push:
    branches:
      - main
      - flutter-forward-23
  pull_request:
    branches:
      - main
      - flutter-forward-23
  schedule:
    - cron: "0 0 * * 0"

# Declare default permissions as read only.
permissions: read-all

env:
  NODE_ENV: production
  NODE_VERSION: 18

jobs:

  test:
    runs-on: ubuntu-latest
    if: github.repository == 'flutter/website-private'
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Beta channel"
            branch: beta
            experimental: true
          - name: "Stable channel"
            branch: stable
            experimental: false
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          submodules: recursive
      - name: Test
        run: make test FLUTTER_TEST_BRANCH=${{ matrix.branch }}
        continue-on-error: ${{ matrix.experimental }}
