name: build

on:
  push:
    branches:
      - main
      - io22-working
  pull_request:
    branches:
      - main
      - io22-working
  schedule:
    - cron: "0 0 * * 0"

# Declare default permissions as read only.
permissions: read-all

env:
  NODE_ENV: production
  NODE_VERSION: 17

jobs:

  test:
    runs-on: ubuntu-latest
    if: github.repository == 'flutter/website-private'
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Beta channel"
            channel: beta
            experimental: false
          - name: "Stable channel"
            channel: stable
            experimental: true
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: Test
        run: make test
        env:
          TEST_TARGET_CHANNEL: ${{ matrix.channel }}
        continue-on-error: ${{ matrix.experimental }}
