name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"

# Declare default permissions as read only.
permissions: read-all

env:
  NODE_ENV: production
  NODE_VERSION: 18

jobs:

  test:
    runs-on: ubuntu-latest
    if: github.repository == 'flutter/website'
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Beta channel"
            branch: beta
            experimental: true
          - name: "Stable channel"
            branch: stable
            experimental: false
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          submodules: recursive
      - name: Test
        run: make test FLUTTER_TEST_BRANCH=${{ matrix.branch }}
        continue-on-error: ${{ matrix.experimental }}

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push'
      && github.ref == 'refs/heads/main'
      && github.repository == 'flutter/website'
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          submodules: recursive
      - name: Build site and check links
        run: make build
      - name: Install Node for Firebase install
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install Firebase CLI
        run: npm install -g firebase-tools@11.27.0
      - name: Deploy to Firebase hosting
        run: make deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_ALIAS: default

  stage:
    permissions:
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
        with:
          submodules: recursive
      - name: Build site and check links
        run: make build BUILD_CONFIGS=_config.yml,_config_stage.yml
      - name: Stage site on Firebase
        if: ${{
          github.event.pull_request.head.repo.full_name == github.repository &&
          github.event.pull_request.user.login != 'dependabot[bot]' }}
        uses: FirebaseExtended/action-hosting-deploy@4d0d0023f1d92b9b7d16dda64b3d7abd2c98974b
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.SERVICE_KEY }}
          projectId: flutter-docs-prod
