name: HTML link references validate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_ENV: production
  NODE_VERSION: 15

jobs:
  check_link_references:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Build
        run: make build
        env:
          DISABLE_TESTS: 1
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - run: pip install PyYAML
      - run: python tool/check_link_references.py
