name: Check links and link references

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Declare default permissions as read only.
permissions: read-all

jobs:
  check_link_references:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f
        with:
          submodules: "recursive"
      - name: Build and check links
        # Runs tool/check-links.sh as part of build
        # Overrides {{site.url}} to localhost:5500 since the site use absolute URLs
        run: make build BUILD_CONFIGS=_config.yml,_config_link_check.yml
